/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_VentanaPrincipal;

/**
 *
 * @author Silvia Araya J
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private Controlador_VentanaPrincipal controlador;
    
    public VentanaPrincipal() {
        initComponents();
        this.controlador = new Controlador_VentanaPrincipal();
        this.bn_salida.addActionListener(controlador);
        this.menuManipula.addActionListener(controlador);
        this.jmenuConsulta.addActionListener(controlador);
        this.jmenuReportes.addActionListener(controlador);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_principal = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        btn_salir = new javax.swing.JMenu();
        bn_salida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuManipula = new javax.swing.JMenuItem();
        jmenuConsulta = new javax.swing.JMenuItem();
        jmenuReportes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo.jpg"))); // NOI18N

        btn_salir.setText("Archivo");

        bn_salida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        bn_salida.setText("Salir");
        bn_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_salidaActionPerformed(evt);
            }
        });
        btn_salir.add(bn_salida);

        menuPrincipal.add(btn_salir);

        jMenu2.setText("Estudiantes");

        menuManipula.setText("Manipula Estudiantes");
        menuManipula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManipulaActionPerformed(evt);
            }
        });
        jMenu2.add(menuManipula);

        jmenuConsulta.setText("Consulta Estudiantes");
        jMenu2.add(jmenuConsulta);

        jmenuReportes.setText("Reporte Estudiantes");
        jMenu2.add(jmenuReportes);

        menuPrincipal.add(jMenu2);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bn_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_salidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bn_salidaActionPerformed

    private void menuManipulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManipulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuManipulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bn_salida;
    private javax.swing.JMenu btn_salir;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmenuConsulta;
    private javax.swing.JMenuItem jmenuReportes;
    private javax.swing.JLabel lbl_principal;
    private javax.swing.JMenuItem menuManipula;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
